wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Bounding Box Debugger/Images_wandb_delimeter_predictions:
        key: Bounding Box Debugger/Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': 1p
          '1': 2p
          '10': 1m
          '11': 2m
          '12': 3m
          '13': 4m
          '14': 5m
          '15': 5mr
          '16': 6m
          '17': 7m
          '18': 8m
          '19': 9m
          '2': 3p
          '20': 1s
          '21': 2s
          '22': 3s
          '23': 4s
          '24': 5s
          '25': 5sr
          '26': 6s
          '27': 7s
          '28': 8s
          '29': 9s
          '3': 4p
          '30': ton
          '31': nan
          '32': sha
          '33': pei
          '34': haku
          '35': hatsu
          '36': chun
          '37': hand_ton_1
          '38': hand_ton_2
          '39': hand_ton_3
          '4': 5p
          '40': hand_ton_4
          '41': hand_nan_1
          '42': hand_nan_2
          '43': hand_nan_3
          '44': hand_nan_4
          '45': round_0
          '46': round_1
          '47': round_2
          '48': round_3
          '49': round_4
          '5': 5pr
          '50': round_5
          '51': round_6
          '52': round_7
          '53': round_8
          '54': round_9
          '55': team_drivens
          '56': team_exfurinkazan
          '57': team_kadokawa
          '58': team_konami
          '59': team_abemas
          '6': 6p
          '60': team_segasammy
          '61': team_raiden
          '62': team_pirates
          '7': 7p
          '8': 8p
          '9': 9p
    cli_version: 0.10.25
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    t:
      1:
      - 1
      - 3
      4: 3.8.9
      5: 0.10.25
      8:
      - 3
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: ''
data:
  desc: null
  value: .\yolov5-master\data\coco128.yaml
data_dict:
  desc: null
  value:
    download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip
    names:
    - 1p
    - 2p
    - 3p
    - 4p
    - 5p
    - 5pr
    - 6p
    - 7p
    - 8p
    - 9p
    - 1m
    - 2m
    - 3m
    - 4m
    - 5m
    - 5mr
    - 6m
    - 7m
    - 8m
    - 9m
    - 1s
    - 2s
    - 3s
    - 4s
    - 5s
    - 5sr
    - 6s
    - 7s
    - 8s
    - 9s
    - ton
    - nan
    - sha
    - pei
    - haku
    - hatsu
    - chun
    - hand_ton_1
    - hand_ton_2
    - hand_ton_3
    - hand_ton_4
    - hand_nan_1
    - hand_nan_2
    - hand_nan_3
    - hand_nan_4
    - round_0
    - round_1
    - round_2
    - round_3
    - round_4
    - round_5
    - round_6
    - round_7
    - round_8
    - round_9
    - team_drivens
    - team_exfurinkazan
    - team_kadokawa
    - team_konami
    - team_abemas
    - team_segasammy
    - team_raiden
    - team_pirates
    nc: 63
    train: coco128\coco128/images/train2017/
    val: coco128\coco128/images/train2017/
device:
  desc: null
  value: '0'
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 6000
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 16
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: ''
    data: .\yolov5-master\data\coco128.yaml
    device: '0'
    entity: null
    epochs: 6000
    evolve: false
    exist_ok: false
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.01
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 1.0
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs\train\exp17
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 16
    upload_dataset: false
    weights: yolov5s.pt
    workers: 2
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp17
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 16
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 2
world_size:
  desc: null
  value: 1
